name: Build and Push Web API Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: studentapiregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build . -t studentapiregistry.azurecr.io/studentapi:${{ github.sha }}

    - name: Push Docker image to ACR
      run: |
        docker push studentapiregistry.azurecr.io/studentapi:${{ github.sha }}
