name: Trigger auto deployment for studentapi-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/studentapi-app-AutoDeployTrigger-acf09773-98cb-4ec6-8b0c-34afa9c53bad.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.STUDENTAPIAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.STUDENTAPIAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.STUDENTAPIAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: studentapiregistry.azurecr.io
          registryUsername: ${{ secrets.STUDENTAPIAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.STUDENTAPIAPP_REGISTRY_PASSWORD }}
          containerAppName: studentapi-app
          resourceGroup: forstudents
          imageToBuild: studentapiregistry.azurecr.io/studentapi-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


